version: 0.0
os: linux
files:
   - source: /
     destination: ~/var/www/html
permissions:
   - object: ~/var/www/html
     pattern: "**"
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/stopnodeserver.sh
      runas: root
   AfterInstall:
    - location: scripts/startnodeserver.sh
runas: root
